[build]
builder = "nixpacks"
buildCommand = "./gradlew build"

[deploy]
startCommand = "java -jar build/libs/alkaa-backend.jar"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 